### ISSUE TITLE
Package 'livox2_ctrl' not found

### ISSUE THREAD

**Issue by xiaorui3** [shirok1/pylivox2#1]
colcon build --symlink-install
Starting >>> livox2_ctrl
Finished <<< livox2_ctrl [1.55s]          

Summary: 1 package finished [3.63s]
我启动的时候使用ros2 run livox2_ctrl daemon命令，给我一个Package 'livox2_ctrl' not found未找到包

**Comment by xiaorui3** [comment]
运行了export ROS_LOCALHOST_ONLY=1

**Comment by shirok1** [comment]
您 build 之后是不是没有 source install/local_setup.bash
