### ISSUE TITLE
是否支持所有Livox 激光雷达？

### ISSUE THREAD

**Issue by lgl531558674** [shirok1/pylivox2#2]
请问该SDK 是否支持所有Livox 激光雷达？还是只支持"hap"和"mid-360"？

**Comment by shirok1** [comment]
支持范围与 https://github.com/Livox-SDK/Livox-SDK2 相同，目前只支持 HAP 和 Mid-360

**Comment by lgl531558674** [comment]
您好：
很高兴能得到您的回复，我想请问您这边有无计划写一版支持范围与&nbsp;https://github.com/Livox-SDK/Livox-SDK相同的python SDK?


星空瞭望
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shirok1/pylivox2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年4月5日(星期五) 下午4:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shirok1/pylivox2] 是否支持所有Livox 激光雷达？ (Issue #2)





 
支持范围与 https://github.com/Livox-SDK/Livox-SDK2 相同，目前只支持 HAP 和 Mid-360

**Comment by shirok1** [comment]
两版 SDK（或者说两版通信协议）实际上并没有多少共同之处（包括通信的逻辑），难以容进同一套代码（甚至没有多少可以共享的代码），再加上这个项目本身也只是出于个人需要而开发，因此不会考虑添加 SDK1 的支持，建议考虑新开一个项目
